<a href="https://colab.research.google.com/github/sanghavividhi/Natural-Language-Processing-NLP-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

raw_data=[10,20,30]

arr=np.array(raw_data)
print(arr)

[10 20 30]


In [ ]:
blank_canvas=np.zeros((3,3))
print(blank_canvas)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones(5)
print(arr)
arr=np.ones((2,4))
print(arr)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr=np.arange(start=0,stop=10,step=2)
print(arr)
arr=np.arange(1,11)
print(arr)

[0 2 4 6 8]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr=np.eye(3)
print(arr)
arr=np.eye(4)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr=np.random.rand(3,3)
print(arr)

[[0.46520876 0.84702948 0.10587389]
 [0.36624155 0.97106592 0.55710262]
 [0.20373683 0.09624385 0.5570849 ]]


In [ ]:
arr=np.random.randint(1,21,(3,3))
print(arr)

[[11 17 15]
 [ 7 13 14]
 [17 20  8]]


In [ ]:
arr=np.random.choice([1,5,7,9,11],size=(3,3))
print(arr)

[[11  5  5]
 [ 9  7  7]
 [11  9  7]]


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr)
print(arr[2])
print(arr[1:4])
print(arr[-1])

[10 20 30 40 50]
30
[20 30 40]
50


In [ ]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(arr)
print(arr[0,1])
arr[0,1]=20
print(arr)
print(arr[:,1])
print(arr[0,:])
print(arr[0:2,1:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[ 1 20  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[20  6 10]
[ 1 20  3  4]
[[20  3  4]
 [ 6  7  8]]


In [ ]:
arr=np.arange(1,13)
print(arr)
arr1=arr.reshape(3,4)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
list1=[1,2,3,4,5]
arr1=np.array([1,2,3,4,5])
print(list1*2)
print(arr1*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,2,2,2,2])
print("add=",arr1+arr2)
print('power=',arr1**2)

add= [3 4 5 6 7]
power= [ 1  4  9 16 25]


In [ ]:
arr1=np.array([[1,2],[1,2]])
arr2=np.array([[5,5],[5,5]])
print("add=",arr1+arr2)

add= [[6 7]
 [6 7]]


In [ ]:
arr1=np.array([10,20,30,40,50])
print("Min =",np.min(arr1))
print("Max =",np.max(arr1))
print("Sum =",np.sum(arr1))
print("sqrt =",np.sqrt(arr1))
print("mean =",np.mean(arr1))
print("std =",np.std(arr1))
print("exp =",np.exp(arr1))

Min = 10
Max = 50
Sum = 150
sqrt = [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
mean = 30.0
std = 14.142135623730951
exp = [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
print("Min =",np.min(arr1))
print("Max =",np.max(arr1))
print("sum =",np.sum(arr1))
print("sqrt =",np.sqrt(arr1))
print("mean =",np.mean(arr1))
print("std =",np.std(arr1))
print("exp =",np.exp(arr1))

Min = 1
Max = 6
sum = 21
sqrt = [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
mean = 3.5
std = 1.707825127659933
exp = [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [ ]:
arr=np.arange(1,11)
print(arr)
arr1=arr.reshape(2,5)
print(arr1)
arr2=arr*2
print(arr2)
print("Max =",np.max(arr2))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 2  4  6  8 10 12 14 16 18 20]
Max = 20


In [ ]:
#task1,2
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix)
print("Mean =",np.mean(matrix))
print("Sum =",np.sum(matrix))
print("Max =",np.max(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean = 5.0
Sum = 45
Max = 9


In [ ]:
#task3
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
c=a+b
print("matrix a:")
print(a)
print("matrix b:")
print(b)
print("addition:")
print(c)

matrix a:
[[1 2]
 [3 4]]
matrix b:
[[5 6]
 [7 8]]
addition:
[[ 6  8]
 [10 12]]


In [ ]:
#task4
arr=np.array([1,2,3,4,5,6,7,8,9,10])
even=arr[arr % 2 == 0]

print("Original Array:", arr)
print("Even Numbers:",even)

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Even Numbers: [ 2  4  6  8 10]


In [ ]:
#task5
matrix=np.random.randint(1,11,(3,3))
print(matrix)
transpose=matrix.T
print(transpose)

[[10 10  8]
 [ 1  2 10]
 [ 6  6  7]]
[[10  1  6]
 [10  2  6]
 [ 8 10  7]]


In [ ]:
#task6
#create the array
arr=np.array([[10,20,30,40],
              [50,60,70,80],
              [90,100,110,120]])
print(arr)

#print first row
print(arr[0])

#print the last column
print(arr[:,-1])

#print the middle two columns
print(arr[:,1:3])

#print the last two rows
print(arr[1:])

#replace 110 with 999
arr[arr == 110] = 999
print(arr)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[10 20 30 40]
[ 40  80 120]
[[ 20  30]
 [ 60  70]
 [100 110]]
[[ 50  60  70  80]
 [ 90 100 110 120]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 999 120]]


In [ ]:
#task7
#create random array of 25 integers(1to100)
arr=np.random.randint(1,101,25)
print(arr)

#extract all even numbers
even=arr[arr % 2 == 0]
print(even)

#extract all odd numbers
odd=arr[arr % 2 != 0]
print(odd)

#count the number of even and odd elements
len(even)
len(odd)

#find the average of only even numbers
if len(even)>0:
  print("\nAverage of Even Numbers:",np.mean(even))
else:
  print("\nNo even numbers found")

[80 77 83 40 53 83 75 57 36 20 76 94 29 49 35 65 96 67 31 28 31 11 76 22
 77]
[80 40 36 20 76 94 96 28 76 22]
[77 83 53 83 75 57 29 49 35 65 67 31 31 11 77]

Average of Even Numbers: 56.8
